CREATE DATABASE STORE;

USE STORE;

CREATE TABLE CATEGORIES(
	name VARCHAR(30) NOT NULL UNIQUE,
	id INT auto_increment NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

SELECT * FROM CATEGORIES;


CREATE TABLE PRODUCTS(
	id INT auto_increment NOT NULL UNIQUE,
	title VARCHAR(30) NOT NULL UNIQUE,
	desc_pdt TEXT,
	favorite BOOL,
	price VARCHAR(30) NOT NULL,
	img_url TEXT,
	category INT,
	FOREIGN KEY (category)
	REFERENCES CATEGORIES(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);